### ISSUE TITLE
Allow creating marker clusters

### ISSUE THREAD

**Issue by Sebobo** [webexcess/openstreetmap#6]
I'm using this package on Neos.io for the new service provider listing and I as some cities have multiple providers I need marker clusters.

Did you already integrate something like https://github.com/Leaflet/Leaflet.markercluster with this package or do you plan do this?

Would be great if we could implement this feature together.

**Comment by sbruggmann** [comment]
Hi @Sebobo 
Thank you for using our package :-)

We thought about that too.
Maybe we don't integrate it directly, because there are many different options. But we wanna make it possible to extend.

What you think about a hook like this: https://github.com/sbruggmann/openstreetmap/tree/feature/map-hooks

Then you integrate the Leaflet.markercluster CSS and JS, add a custom Function like `var myAddMarkersLayerHook = function (layer) { var clusterMarkers = L.markerClusterGroup(); return clusterMarkers.addLayer(layer); }` somewhere before `window.openStreetMap.init`, and enable the Hook via Fusion:
```
prototype(WebExcess.OpenStreetMap:Map.Component) {
    mapHooks {
        addMarkersLayerHook = 'myAddMarkersLayerHook'
    }
}
```

**Comment by Sebobo** [comment]
Sounds great, can try it if it solves the issue and get back to you

**Comment by Sebobo** [comment]
Works perfect :)

**Comment by sbruggmann** [comment]
It's now documented: https://github.com/webexcess/openstreetmap/blob/master/README.md#markercluster-example
